server:
  port: 8080

request:
  control:
    enabled: true
    default-enabled: true
    secret-key: "470727"
    control-path: "/set-request"
    log-enabled: true
    reject-message: "系统维护中，请稍后再试"
    whitelist-paths:
      - "/set-request/**"
      - "/actuator/**"
      - "/error"
      - "/favicon.ico"

logging:
  level:
    com.luckcoder.request.control: INFO
    root: INFO